Added social links to main page
bigtinytales/bigtinytales.github.io pull request #5
Opened 2023-09-14 15:15 UTC by JFelz

The images are temporary. I just wanted to add the functionality. I can create a more BTT-style image link for each one now.

2023-09-22 16:24 UTC, JFelz commented
Working on the Social Link graphics, will add those .png files in the folder in the next Pull Request.

2023-09-22 22:41 UTC, jjsub requested changes

2023-09-22 22:41 UTC, jjsub commented on index.html
> +        <div class="AboutUs">
Remove the code of about from this PR

2023-09-22 22:44 UTC, jjsub commented on style.css
> +    padding: 5px;
Also primo use `em` and not px 

This is better for different screen resolutions and sizes

2023-09-22 22:45 UTC, jjsub commented
@JFelz Could you please provide screenshots of the UI work related to this PR 

One screenshot for desktop view and one screenshot in mobile view. 

Thanks

2023-09-27 22:34 UTC, jjsub commented
@JFelz How is your timing on the updates? 

Would you like me to merge your chanes and then I make the changes myself. If that's okay with you I can go ahead and do that. 

Waiting for you res

2023-09-28 19:47 UTC, JFelz commented
Screenshot in mobile view :
![image](https://github.com/bigtinytales/bigtinytales.github.io/assets/34929951/00c9de3f-b310-46d6-8544-85440f60ae06)

Screenshot in Desktop view:
![image](https://github.com/bigtinytales/bigtinytales.github.io/assets/34929951/721b6a14-59d5-416f-b343-ddaf20bb7385)

2023-09-28 19:53 UTC, JFelz reviewed
Updated the measurement types and removed the about section as requested

2023-09-28 19:54 UTC, merged